language: go

go:
  - 1.11.x

script:
  - go test -v ./...

before_deploy:
  - go get github.com/mitchellh/gox
  - go get github.com/tcnksm/ghr

deploy:
  provider: script
  script: ./release.sh
  on:
    tags: true
    branch: master
